### ISSUE TITLE
[FEATURE] Configure ports used by go-langserver

### ISSUE THREAD

**Issue by sbward** [ckaznocha/ide-go#14]
I am using the latest version of:
-   [x] Atom
-   [x] ide-go
-   [x] atom-ide-ui
-   [x] go-langserver

**Operating System**: MacOS 10.13.3

### Problem

The port `:6060` is used by go-langserver for pprof, and `:4389` is used for the language service.

As a developer it's possible for one of these ports to be used by other software on my machine.  In my case, `:6060` is being used by something else.

### Request

Add the `-pprof` and `-addr` options for go-langserver to the package settings, so they can be changed by the user.

**Comment by ckaznocha** [comment]
I added an option to configure the pprof port. It is actually a misleading setting, the docs make it seem like it pprof should be disabled by default but its actually running on `:6060` by default and there is no way to disable it. I hope this option is the workaround you needed!

I didn't add an option for `-addr` because that's only used in `tcp` mode and this plugin uses `stdio`. No tcp server is started so it should never cause a conflict on `:4389`
