### ISSUE TITLE
Go language server stopped unexpectedly.

### ISSUE THREAD

**Issue by yefremov** [ckaznocha/ide-go#20]
I am using the latest version of:
-   [x] Atom
-   [x] ide-go
-   [x] atom-ide-ui
-   [x] go-langserver

**Operating System**:
macOS High Sierra
version 10.13.3

```
$ go version
go version go1.9.4 darwin/amd64
```

<img width="473" alt="screen shot 2018-02-09 at 16 20 51" src="https://user-images.githubusercontent.com/59296/36032058-6c020b34-0db5-11e8-9e2f-571a69b6884f.png">

This error is thrown whenever a go source files is open, also navigation through symbols doesn't work.

**Comment by sarahhodne** [comment]
I got this due to having an outdated version of go-langserver. Double-check that you have the latest version? (`go get -u github.com/sourcegraph/go-langserver`)

The problem for me was that the `-gocodecompletion` flag wasn't included in my older version of go-langserver, so I was also able to "fix" it by disabling code completion in the settings for ide-go.

**Comment by ckaznocha** [comment]
Sorry about the trouble @yefremov and @sarahhodne. You should now get prompted to update go-langserver if ide-go detects that your version is incompatible
