### ISSUE TITLE
Feature request for outline: TODO

### ISSUE THREAD

**Issue by rodriguise** [ckaznocha/ide-go#27]
I am using the latest version of:
-   [X ] Atom
-   [X ] ide-go
-   [X ] atom-ide-ui
-   [X ] go-langserver

This is a feature request. It would be very awesome if the outline could capture ```//TODO`` comments in some fashion and tier them within the methods if possible. A possible format could be

```// TODO <label>``` 

Thanks for the great tool.

**Comment by ckaznocha** [comment]
Hey @rodriguise,
I think that would be a really cool feature! Unfortunately since its not specifically related to Go or [sourcegraph/go-langserver](https://github.com/sourcegraph/go-langserver) it is outside the scope of this project.

I've been toying with the idea of creating a [language server](https://microsoft.github.io/language-server-protocol/) for [Codetag](https://www.python.org/dev/peps/pep-0350/) like text patterns. I think  something like that would be really awesome, not too much work to create, and provide the kind of seamless integration you're looking for. I don't really have time to undertake a new project right now but if I do end up making one I'll post it here.

In the meantime there are a few linter plugins that would show the kind of info you want in the diagnostics panel you could try out. I use this one and have been very happy with it: [linter-annotations](https://atom.io/packages/linter-annotations)

Thanks!
